[DEV-1219] feat(credentials): Holder-Integrate Credentials verification -> Added VC body validation on verification & tests
cheqd/did-jwt-vc pull request #1
Opened 2022-05-17 20:13 UTC by Eengineer1

- Credential payload - JWT payload equality extension.

2022-05-19 15:37 UTC, ankurdotb requested changes
I'm gonna reset this PR to draft, so that we get the chance to incorporate linting etc workflows first.

I also wouldn't mind a quick review from @askolesov. We've built some validation logic for DIDs in the ledger side, perhaps we could use the same here? Or at least they shouldn't fundamentally be too far away.

2022-05-19 15:37 UTC, ankurdotb commented on package.json
>    "name": "@eengineer1/did-jwt-vc",
Swap to cheqd

2022-05-19 15:37 UTC, ankurdotb commented on package.json
>    "license": "ISC",
Also swap the license to ours (Apache 2.0)

2022-07-04 15:19 UTC, ankurdotb commented
@Eengineer1 Is this one deprecated?

2022-07-04 15:21 UTC, Eengineer1 commented
@ankurdotb Yes, we had switched it to draft, but let's close, if you agree as well.

2022-07-05 00:54 UTC, closed without merging